name: PR Tests

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run all unit tests
      run: dotnet test --configuration Release --no-build --verbosity normal --logger "console;verbosity=detailed"

    - name: Test Summary
      if: always()
      run: |
        echo "## Test Results" >> $GITHUB_STEP_SUMMARY
        echo "All unit tests executed" >> $GITHUB_STEP_SUMMARY

  test-report:
    name: Test Report
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
    - name: Download test results
      uses: actions/download-artifact@v4
      if: always()
      continue-on-error: true

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Unit tests completed. Check the Actions tab for detailed results.'
          })
